### ISSUE TITLE
不同显卡运行时间差别很大

### ISSUE THREAD

**Issue by zhenxing9968** [cunjian/pytorch_face_landmark#15]
我在使用version-RFB-320.onnx检测同一张图片，在2080ti上面运行时间为6-7ms，然而在tesla V100上面运行时间为33ms左右，这是为什么呢？

**Comment by zhenxing9968** [comment]
环境配置也一样的

**Comment by cunjian** [comment]
I have not got a chance to test with different GPUs. Mainly, the speed was evaluated on the CPU.
