### ISSUE TITLE
landmark_detection_56_se_external.onnx

### ISSUE THREAD

**Issue by zahidzqj** [cunjian/pytorch_face_landmark#16]
Can you tell me which backbone is used to train this model?

**Comment by cunjian** [comment]
"MobileNet_GDConv_56" should be the used backbone. You can find the details from the models/basenet.py

**Comment by twmht** [comment]
@cunjian 

where is the referenced training code for this model?

**Comment by sainisanjay** [comment]
> @cunjian
> 
> where is the referenced training code for this model?

@twmht Do you got the answer of your query?
