### ISSUE TITLE
Error: No module named 'src'

### ISSUE THREAD

**Issue by ZihaoCheng001** [cunjian/pytorch_face_landmark#17]
I run the code : "python test_camera_mtcnn_onnx.py", got the following error:

![image](https://user-images.githubusercontent.com/26185398/100192459-f75bff00-2f2c-11eb-98f4-78296897ffec.png)

Seems like the src folder is missing.

**Comment by cunjian** [comment]
I have renamed the src to MTCNN. It should be "from MTCNN import detect_faces".
