### ISSUE TITLE
Profile face alignment performance

### ISSUE THREAD

**Issue by darraghdog** [cunjian/pytorch_face_landmark#19]
Hi,

Thanks for your great work @cunjian maintaining this package. 
I am seeing differences in Profile Face alignment from what is on the README (from Menpo dataset) compared to what I get locally. 
I am using the `MobileNetV2_SE_ExternalData (56×56)` model.
Below you see the results. When the face is turned to the side, the model seems to try to fit two eyes to the face even though only one can be seen. 
I see in your images from Menpo, only one eye seems to be annotated. 

Any ideas what I am doing wrong ?
Thanks,
Darragh. 

![image](https://user-images.githubusercontent.com/7209588/100613365-53979800-330c-11eb-9663-8c4f539186dc.png)

**Comment by cunjian** [comment]
The results you have here are based on the 68-point model. Could you try the recent 68-point model from MobileFaceNet_ExternalData(112×112)?  The MobileNetV2_SE_ExternalData (56×56) is sort of old. Regarding the profile face alignment, that only works for the 39-point and specifically on profile faces. That limits the application scenario. I have not shared the 39-model yet but will try to post it later.

**Comment by darraghdog** [comment]
Thank you @cunjian , I will try it on MobileFaceNet_ExternalData(112×112) and show results. 
Also, this makes sense re the 39 points - 39 points is exclusive to profile face, and 68 is exclusive to non-profile faces.

**Comment by cunjian** [comment]
You are welcome to post the updated results and I would love to see where are the failure cases and how the model can be further improved.

**Comment by darraghdog** [comment]
Here you go, I did not re-project the results into a larger frame; I just took the landmarks from the 112x112 image and applied to a 224X224 cut of the frame. Also added a constant 5 pixel border to bbox. 
The code below to get the sequence of frames if you wish to use it. 
**This model seems a lot more robust.** I will use this. Converting to onnx gave 0.031 seconds for this, vs 0.005 for 56X56 model.

![image](https://user-images.githubusercontent.com/7209588/100642703-05e15680-3331-11eb-920e-c83c1e92e5f0.png)

```
import youtube_dl
import ffmpeg
# Helper function to find the youtube URL
def getm3u8(url):
	yl = youtube_dl.YoutubeDL({'format': 'best'})
	quality = yl.extract_info(url, download=False)
	m3u8 = quality['url']
	width = quality['width']
	height = quality['height']
	fps = quality['fps']
	return m3u8, width, height, fps

def download2numpy(m3u8, width , height, fps = 16):
    out, _ = (
            ffmpeg
            .input(m3u8)
            .filter('fps', fps=fps, round='up')
            .output('pipe:', format='rawvideo', pix_fmt='rgb24')
            .run(capture_stdout=True, quiet = True))
    video = (np.frombuffer(out, np.uint8).reshape([-1, height, width, 3]))  
    return video
# Set some params
URL = 'https://www.youtube.com/watch?v=-CPCs7vVz6s&ab_channel=ErykahBaduVEVO'
FPS = 8
CLIP_LEN = 10
# Extract to numpy array
m3u8, width, height, fps = getm3u8(URL)
video = download2numpy(m3u8, width , height, fps = FPS)
video = video[58*FPS:80*FPS][::2]

```

**Comment by darraghdog** [comment]
@cunjian I will close the issue, thank you for the advice.
