### ISSUE TITLE
Question about landmark coordinates

### ISSUE THREAD

**Issue by CreamNuts** [cunjian/pytorch_face_landmark#23]
Thanks for awesome repo! 

I'm newbie of face detection. I want to get 68 landmark coordinates dictionary, like { nose: [...], eye: [...], ... } using MobileNet. Can I know where the results are located on the face without drawing them?

**Comment by cunjian** [comment]
The positions for the 68-landmarks can be located in Figure 1 of this website. 
https://ibug.doc.ic.ac.uk/resources/300-W/

You can easily extract the landmarks from the output array "landmark".

**Comment by CreamNuts** [comment]
> The positions for the 68-landmarks can be located in Figure 1 of this website.
> https://ibug.doc.ic.ac.uk/resources/300-W/
> 
> You can easily extract the landmarks from the output array "landmark".

Thanks! 

I will close the issue.
