### ISSUE TITLE
OpenCV and PIL.Image is different

### ISSUE THREAD

**Issue by yuhaoooo** [cunjian/pytorch_face_landmark#6]
I think there is a bug. In the 50th line of the [test_batch_mtcnn.py](https://github.com/cunjian/pytorch_face_landmark/blob/master/test_batch_mtcnn.py#L50), the authors use opencv to read images, which is `img = cv2.imread(imgname)`. The default setting of `imread` is BGR channels. However, the default setting of `Image.open` is RGB channels.
So, the cropped images feeded into mobilenet are also BGR channels, which are different with the input images of mtcnn.

**Comment by cunjian** [comment]
They are separate streams. PIL image is only used for MTCNN to detect the bounding box. Once the position is returned, it will be fed into the CV2 image.

**Comment by yuhaoooo** [comment]
Ok, I get it. But I think it should be better that images feeded into pytorch model are dealt with PIL module, and CV2 images are used to display.
