### ISSUE TITLE
Wrong type of loaded images in test_batch_mtcnn.py.

### ISSUE THREAD

**Issue by TaplierShiru** [cunjian/pytorch_face_landmark#8]
Hello, thank you for this repository.
When I try to run `test_batch_mtcnn.py` on test samples (from `samples/12--Group/` folder), python file runs without any errors, but it does not produce any result. 
In the code I found the following:
`filenames=glob.glob("samples/12--Group/*.png")`
but the image in `samples/12--Group/` folder has `.jpg` format which cannot be found by glob with `*.png`.

I think it's better to change this code to something like that:
`filenames=glob.glob("samples/12--Group/*")`
in order to load images of any format.

Or change this line to:
`filenames=glob.glob("samples/12--Group/*.jpg")` 
but in this case it should be pointed out in the README.

Here link to this line:
https://github.com/cunjian/pytorch_face_landmark/blob/ef5ce6226905ea9c910531b271d43cc8f171d264/test_batch_mtcnn.py#L47

**Comment by cunjian** [comment]
see https://github.com/cunjian/pytorch_face_landmark/issues/5
I will fix this to avoid confusion.

**Comment by cunjian** [comment]
Fixed.
