### ISSUE TITLE
detection or prediction

### ISSUE THREAD

**Issue by BehnazDibayee** [cunjian/pytorch_face_landmark#9]
Hi
Thanks for sharing your work.
I test "test_camera_mtcnn_onnx.py" with my webcam and block part of my face with a mask (my mouth and nose). I expect the code to reduce keypoints and only show some of them which were related to lower part of my face. But it didn't. It still showed all keypoints inaccurately and seems to predict them instead of detecting.
Is that a detection or a prediction?

**Comment by cunjian** [comment]
I assume you use the 56*56 MobileNetV2 model. This model has not been trained with occlusion data, nor does it include any occlusion indices. Basically, it will output all 68 landmarks. There is not much difference between detection and prediction. These points are all estimated. You can try the PFLD model. It is better against occlusion. Maybe in the future, I can add the artificially generated mask onto the face, this should help address the problem you mention.
